### ISSUE TITLE
ROBOT_ADDRESS_PREFIX doesn't match current Spheros

### ISSUE THREAD

**Issue by emnullfuenf** [nicklasgav/Sphero-Desktop-API#7]
My Sphero's bluetooth adress starts with 6886. Thus this prefix does not work anymore.

`public static final String ROBOT_ADDRESS_PREFIX = "00066";`

I commented out this line in order to get the library working:

```
if( !this.bt.getAddress().startsWith( ROBOT_ADDRESS_PREFIX ) )
{
  String msg = invalidAddressResponses[Value.clamp( error_num++, 0, invalidAddressResponses.length - 1 )];
  Logging.error( msg );
  throw new InvalidRobotAddressException( msg );
}
```

**Comment by nicklasgav** [comment]
Commented out the section as a temporary fix.
